### ISSUE TITLE
Rechazado

### ISSUE THREAD

**Issue by t0kyolover** [4GeeksAcademy/i-lema-Lista-Contactos-React-Context#1]
- [x] Los archivos de views tienen que empezar con minúscula y AppRouter también
- [x] Los componentes tienen que estar en la carpeta de components, y en views solo las vistas

_BONUS_
- [ ]  _Deja añadir dos contactos con los mismos detalles_
![Screenshot 2024-06-15 at 12 53 19](https://github.com/4GeeksAcademy/i-lema-Lista-Contactos-React-Context/assets/144109471/e6e3568b-a3a3-46c3-ab65-94f8df1d9d4a)

**Comment by i-lema** [comment]
Ya cambié los nombres de las vistas y pasé AgendaContact a la carpeta de componentes, estaba en la de views porque en primer lugar iba a ponerla como otra view, pero no fue necesario y me olvidé de cambiarla. Y AppRouter pensé que iba con mayúscula primero porque Juan lo hizo así, pero ya lo cambié también.
El Bonus más adelante lo intento cambiar, que ahora estoy intentando acabar el proyecto de Star Wars y prefiero darle prioridad a eso
